### ISSUE TITLE
funktioniert nicht am handy

### ISSUE THREAD

**Issue by niwla23** [Lobby-Hoes/wo-ist-vulva#4]
Mögliche Lösung:

Bilder im Hochformat ab ner bestimmten Bildschirmbreite

**Comment by fluffeliger** [comment]
einfach responsive machen mit @media

**Comment by niwla23** [comment]
bilder sind aber nicht responsive xD

**Comment by niwla23** [comment]
oder man muss die vulva positions dynamisch ändern
sonst sind die außerhalb des screens

**Comment by lobbyhoe12345** [comment]
"funktioniert nicht am handy" was heißt das?

**Comment by fluffeliger** [comment]
dann mach die vulva position einfach dynamisch ich glaube das ist das beste was wir machen können
oder am Handy einfahc auf querformat gehen?

**Comment by lobbyhoe12345** [comment]
Die Vulva-Position ist absolut positioniert, relativ zu dem bild mit % werten. Was funktioniert denn nicht aufm handy?

**Comment by eleander56-b** [comment]
> "funktioniert nicht am handy" was heißt das? Bei mir funktioniert das aufm handy

Es funktioniert nur auf Android Handys. Bei IPhones bleibt es auf den Ladebildschirm

**Comment by lobbyhoe12345** [comment]
hab einen fix gepusht 4b828f5f5e1018ece970fa1f37dd2a5531b8d822

**Comment by eleander56-b** [comment]
Bei meinen Tests funktioniert es jetzt

**Comment by niwla23** [comment]
also was ich eigentlich meinte ist das das Format halt ungünstig ist, aber vlt wäre ein hinweis das man das querformat nutzen soll ganz hilfreich.

**Comment by eleander56-b** [comment]
Achso sry.
yess stimmt das wäre ganz gut.
