### ISSUE TITLE
Fehler beim zoomen sowohl am Handy als auch am PC

### ISSUE THREAD

**Issue by eleander56-b** [Lobby-Hoes/wo-ist-vulva#7]
Wenn man die Seite auf Handy oder PC größer zieht verändern sich sowohl der Ausschnitt der Vulva Bilder, als auch die Größe des Lautstärkenknopf/ScoreDisplay.
Dadurch, dass sich der Ausschnitt beim zoomen verändert, ist er dann auch ab und zu in dem Zwischenraum zwischen den Vulva Bildern. Also so:
![image](https://user-images.githubusercontent.com/95469786/163121006-dbf7f2ac-d771-4193-9641-cf053dd8b210.png)
und nicht so:
![image](https://user-images.githubusercontent.com/95469786/163121264-5034af33-78b2-4719-a62c-6a53902a2649.png)

Beim zoomen auf dem Handy kann es auch passieren, dass der Lautstärkenknopf und das ScoreDisplay das komplette spiel verdecken.

**Comment by QTPah** [comment]
Die Grösse der Buttons sind in REM angegeben was relativ zur fontsize ist. Ich würde mal versuchen die Grösse in pixel anzugeben.

**Comment by lobbyhoe12345** [comment]
gefixt, bitte testen und issue schließen

**Comment by eleander56-b** [comment]
Top, danke dir! Das Hauptproblem ist behoben. Das Problem, dass es beim zoomen passieren kann, dass der Lautstärkeknopf und das ScoreDisplay das komplette Spiel verdecken können ist, auf dem IPhone, noch nicht gelöst.

**Comment by eleander56-b** [comment]
Läuft. Mercii @lobbyhoe12345
